name: '$(Build.BuildId)-$(pipelineName)-$(Build.SourceBranchName)'

trigger:
  branches:
    include:
    - DEV
    - SIT
    - UAT
    - PROD
    - DEMO


resources:
  repositories:
  - repository: self 
  - repository: templates
    type: git
    name: VPlatform-Deployment/VPlatform-Deployment

pool:
  vmImage: ubuntu-latest
  
stages:
- stage: BuildPublishandDeploy 
  displayName: Build image, publish to DockerHub and deploy to k8s
  jobs: 
  - template: Pipeline-templates/Jobs/docker_build_publish_deploy.yml@templates
    parameters:
      serviceName: $(serviceName)
      k8sManifestPath: $(k8sManifestPath)
      env_name: $(env)
      chart_Path: $(chart_Path)
      release_Name: $(release_name)
      npmAuthenticate: true
      value_File_Path: $(k8sManifestPath)
      runCodescan: true
      
      


