export const URL_KEYS = [
	"NEXT_PUBLIC_STS_AUTHORITY",
	"NEXT_PUBLIC_VSECURITY_BASE_API_URL",
	"NEXT_PUBLIC_WELCOME_APP_MICROFRONTEND_BASE_URL",
	"NEXT_PUBLIC_VDOCUMENT_BASE_API_URL",
	"NEXT_PUBLIC_ORIGIN",
	"NEXT_PUBLIC_APPBAR_URL",
];

export const NON_URL_KEYS = [
	"NEXT_PUBLIC_CLIENT_ID",
	"NEXT_PUBLIC_RESPONSE_TYPE",
	"NEXT_PUBLIC_CLIENT_SCOPE",
	"NEXT_PUBLIC_APP_MANIFEST_ENVIRONMENT",
];
