import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Main from "@/components/main.component";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Incident Report",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<link rel="icon" href="/favicon.svg" sizes="any" />
			<body className={inter.className}>
				<Main>{children}</Main>
			</body>
		</html>
	);
}
